name: "Daployi Docker Compose Deploy"
description: "Deploy Docker Compose stacks to the Daployi platform from GitHub Actions"

branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  api_token:
    description: "Daployi API token"
    required: true
  project_id:
    description: "Project ID"
    required: false
  variables:
    description: "JSON string of variables to override"
    required: false
  api_url:
    description: "The base URL of the Daployi instance"
    required: true
  timeout:
    description: "Timeout in minutes for waiting for the deployment to finish"
    required: false
    default: "60"

runs:
  using: "node24"
  main: "dist/index.js"
